### ISSUE TITLE
Performance test for PGP encryption

### ISSUE THREAD

**Issue by Arsnael** [linagora/openpaas-james#101]
We need to...

 - Evaluate latency increase upon low load.
 - Speed mail processing

**Comment by Arsnael** [comment]
+ SMTP benchmark
=> enable encryption on preprod? send emails, measure

**Comment by Arsnael** [comment]
https://james-charge-02.open-paas.org/job/Gatling-job/360/ => smtp simulation no encryption

**Comment by Arsnael** [comment]
Simulation parameters:
* SmtpNoAuthenticationNoEncryptionMixedBodySimulation 
* Number of users: 5 (each user sends 2 mails per second (a normal and a big one) so we have around 10 mails per seconds)
* Injection duration: 1 minutes
* Scenario duration: 10 minutes
* Image used: linagora/tmail-backend:distributed-branch-master

## Normal setup

Just a default James distributed setup.

### No encryption

* Average response time:
![response-time-avg.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/c49df648-9b8a-4ff7-a43f-18f6c9aa339a)
* Response time percentiles:
![response-time-percentile.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/12a8579a-c228-49a3-ba20-1bdca42cae02)
* Slow traces:
![slow-traces.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/a78b8ca0-68e4-46ac-88da-2a16cff0cba0)
* Queries:
![queries.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/121a82ea-d8d1-4ef9-b2c3-82e5eb78dd7e)

### Encryption

* Average response time:
![response-time-avg.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/8734b8d8-3a45-4006-ae23-d6f265478b48)
* Response time percentiles:
![response-time-percentiles.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/b22c1906-8b0d-429e-bc19-c564a137e3b9)
* Slow traces:
![slow-traces.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/2b049a96-99ef-44b6-aa98-97e672e6189f)
* Queries:
![queries.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/a71b2093-74ea-47f8-bb44-03695305c9c0)

### Conclusion

The average response time is 10 times slower and the 99th percentile 5 times slower. Huge performance degradation.

## Number of threads for mail processing

Then we decided to decrease the number of threads for mail processing, from 20 to 4 ( in mailetcontainer.xml)

### No encryption

* Average response time:
![screenshot-james-charge-01_4000-2021.05.04-17_45_44.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/7954d37f-c88c-4b58-a5f2-627592fc8fe9)
* Response time percentiles:
![screenshot-james-charge-01_4000-2021.05.04-17_45_58.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/5c6dd797-ff95-4136-888f-8fd88a696765)
* Slow traces:
![screenshot-james-charge-01_4000-2021.05.04-17_46_17.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/e5995515-d5b9-4137-8ff9-b135c4b93797)
* Queries:
![screenshot-james-charge-01_4000-2021.05.04-17_46_44.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/4e5ac520-49f4-4cfa-b21e-f3b18b31e22a)

### Encryption

* Average response time:
![screenshot-james-charge-01_4000-2021.05.04-18_04_33.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/865a1a59-39a2-4cb4-942e-be42c46d852e)
* Response time percentiles:
![screenshot-james-charge-01_4000-2021.05.04-18_04_53.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/1151bed6-afc8-42f6-adbc-caecc4e7ca31)
* Slow traces:
![screenshot-james-charge-01_4000-2021.05.04-18_05_28.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/d78811c7-1b80-4e6f-8c60-2a02a872afa6)
* Queries:
![screenshot-james-charge-01_4000-2021.05.04-18_06_02.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/587dfa11-ca2f-44a6-bd4a-2b60ae0cce14)

### Conclusion

This tweak enabled a good enhancement already. Now the encryption is 5 times slower in average response time and 2 times slower in 99th percentile.

## Using buffered encrypted streams

We kept the same params as latest simulation (so nb of threads = 4) and we used this work from Benoit using buffered encrypted stream before writing it on the file system https://github.com/linagora/openpaas-james/pull/140

### No encryption

* Average response time:
![screenshot-james-charge-01_4000-2021.05.05-10_24_05.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/24e38049-454a-4da3-b272-7f9d8a59e653)
* Response time percentiles:
![screenshot-james-charge-01_4000-2021.05.05-10_24_22.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/df8c83c1-6b93-4ffd-b0ef-5e3fa4d61849)
* Slow traces:
![screenshot-james-charge-01_4000-2021.05.05-10_24_35.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/5c3dba1e-d81d-44bf-959e-e715d233ede7)
* Queries:
![screenshot-james-charge-01_4000-2021.05.05-10_25_34.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/a8338558-54b7-412e-8ad3-7df9493062ad)

### Encryption

* Average response time:
![screenshot-james-charge-01_4000-2021.05.05-10_44_52.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/1d7ce49d-f16e-4a22-8af3-d575fab90e90)
* Response time percentiles:
![screenshot-james-charge-01_4000-2021.05.05-10_45_11.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/77857506-e1b4-42d3-af3f-cbfd4be5b2eb)
* Slow traces:
![screenshot-james-charge-01_4000-2021.05.05-10_45_50.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/3e863ef7-229b-4088-9655-07a9a501b821)
* Queries:
![screenshot-james-charge-01_4000-2021.05.05-10_46_04.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/2a3290fa-d772-406f-a02c-96170a90c841)

### Conclusion

This extra work brings similar performance results between no encryption and encryption. It definitely enhances the system performances.

**Comment by vttranlina** [comment]
About `Queries`,  Encryption always has more performance than NoEncryption?

**Comment by Arsnael** [comment]
> About `Queries`, Encryption always has more performance than NoEncryption?

Not sure... Could be influenced by the fact that there is a warmup phase, and also that I didn't always wait the encryption to finish dequeuing everything before taking a screenshot. Might not be very accurate results
