### ISSUE TITLE
Filter/get as an openpaas-james specific commands

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#11]
Add FilterGetMethod in jmap submodule.

Initialize integration tests (just like in apache/james-project)

Bind it in the apps

**Comment by rouazana** [comment]
There is no plan to propose this as an official JMAP extension first?

**Comment by chibenwa** [comment]
> There is no plan to propose this as an official JMAP extension first?

This extension is highly coupled with the MUA business rule and thus would hurt inter-operability.

Inter-operability being the primary concern of the IETF, I think it makes little sense to push toward it.

Moreover, there is a concurrent effort (sieve over JMAP), at the other end of the spectrum, and the debate SIEVE VS tight business rules had been held some years ago.

Also, the ability to have "filters" is a nice differenciator for the Linagora james extensions (that we want people to eventually use ;-) )
