### ISSUE TITLE
JenkinsFile that runs locally

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#29]
3 phase:

 - 1. Fetch apache/james-project code 
 - 2. Compile (install) at root (it will compile apache/james-project then openpaas-james)
 - 3. Run tests (mvn test) within openpaas james subfolder (no need to test james-project as it is separatedly tested.)

Using https://github.com/jenkinsci/jenkinsfile-runner I am able to run the Jenkins file locally

**Comment by Arsnael** [comment]
From @rouazana :

> I started the work on Jenkins local runner, see https://github.com/linagora/openpaas-james/tree/jenkins-runner-1 and https://github.com/linagora/openpaas-james/tree/jenkins-runner-2 but for now it's not working. First strategy is based on https://github.com/jenkinsci/jenkinsfile-runner/tree/master/demo/git-maven but I don't succeed to have a docker image as an agent. Second strategy is based on https://github.com/jenkinsci/jenkinsfile-runner/tree/master/demo/cwp-jdk11 but it's not building for whatever reason
