### ISSUE TITLE
PR build

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#32]
Rebase the PRs on master then build & test them. Build output should be visible on Github.

      - test this please (Should have)
      - build phase report in github (Nice to have)

**Comment by Arsnael** [comment]
Might need devops support

**Comment by Arsnael** [comment]
https://ci.linagora.com/linagora/lrs/saas/deployments/linagora/load-tests-preprod-emaily-applications/merge_requests/1 
Fetch, merge on master and build PR

Missing:
test this please
build phase report in github

**Comment by Arsnael** [comment]
New updates:
https://ci.linagora.com/rcordier/james-ci/merge_requests/2
https://github.com/linagora/openpaas-james/pull/52

Building PRs, posting results in github.
Missing:
+ test this please -> workaround would be to rebuild from CI, as PR are being separated in a tree folder
+ phase output github -> would need more time and tuning
