### ISSUE TITLE
Produce simple docker images with JIB

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#6]
Based on jdk 11 images

DOD:

 - You are able to start all 3 servers in docker

 - You provide a dockercompose for the distributed server (use networks, not links)

**Comment by Arsnael** [comment]
https://github.com/linagora/openpaas-james/pull/14 for JIB on memory has been merged

**Comment by chibenwa** [comment]
TODO

 - [ ] Glowroot for distributed
 - [ ] CLI for distributed
 - [ ] Glowroot for distributed-ldap
 - [ ] CLI for distributed-ldap
