### ISSUE TITLE
JIB: package the CLI

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#7]
Proposed solution: runtime dependency to the cli project, and a cli.sh script doing the complicated java command call, overriding the main class <3)

DOD: You are able to run CLI commands within the 3 containers
DOD: add integration test showing that the CLI is working for the 3 containes (eg. list domains)

**Comment by Arsnael** [comment]
I don't see CLI yet in the 3 containers, so not closed...

**Comment by chibenwa** [comment]
See https://github.com/linagora/openpaas-james/issues/6#issuecomment-764417178
