### ISSUE TITLE
Filter versionning

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#72]
# Why?

When doing a `Filter/get` / `Filter/set`, version properties (`state` / `newState`/ `oldState`) needs to be specified.

This ensures the clients is aware of changes.

# What ?

```
{
  "sessionState": "${SESSION_STATE.value}",
  "methodResponses": [[
    "Filter/get", {
      "accountId": "$generateAccountIdAsString",
      "state": "36",
      "list": [
      {
        "id": "singleton",
        "rules": [
          {
            "name": "My first rule",
            "condition": {
              "field": "subject",
              "comparator": "contains",
              "value": "question"
            },
            "action": {
              "appendIn": {
                "mailboxIds":["$generateMailboxIdForUser"]
              }
            }
          }
        ]
      }
    ],
    "notFound": []
  }, "c1"]]
}
```

And idem for `Filter/set` oldState/newSate properties.

# How?

As part of James project:

Modify `FilteringManagement` API so that it allows being aware of version changes.

```
class Version {
   private final int version;
   // ... etc ...
}

class UserRules {
   private final Version version;
   private final User user;
   private final List<Rule> rules;
}
```

```
public interface FilteringManagement {
    Publisher<Version> defineRulesForUser(Username username, List<Rule> rules);

    default Publisher<Version> defineRulesForUser(Username username, Rule... rules) {
        return defineRulesForUser(username, Arrays.asList(rules));
    }

    default Publisher<Version> clearRulesForUser(Username username) {
        return defineRulesForUser(username, ImmutableList.of());
    }

    Publisher<UserRules> listRulesForUser(Username username);
}
```

You will then modify FilterGetResponse + FilterSetResponse to include state properties.

**Comment by Arsnael** [comment]
Why not reusing the state with eventBus instead of the version here, like the other jmap methods?

**Comment by chibenwa** [comment]
> Why not reusing the state with eventBus instead of the version here, like the other jmap methods?

EventSourcing offers us state management out of the box.

We might need to generify the concept of state

**Comment by quantranhong1999** [comment]
It looks like I will have to change the other code in James following FilteringManagement changes. 
Is there any strategy to avoid changing?
And if not, how do I know where I should change the code also? (as I know there is a lot of method/ class/test using the old FilteringManagement)

**Comment by chibenwa** [comment]
> It looks like I will have to change the other code in James following FilteringManagement changes.

Yes

> Is there any strategy to avoid changing?

No. It is not a problem, the changes are simple.

> how do I know where I should change the code also? (as I know there is a lot of method/ class/test using the old FilteringManagement)

You do minimal changes so that it compiles and unit test passes.
