### ISSUE TITLE
JIB: package glowroot

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#8]
Add a maven build phase for downloading it (download-maven-plugin) then use the adding jar plugins to do the work...

DOD: Glowroot usage on top of the 3 containers (memory, distributed, distributed-ldap).

**Comment by rouazana** [comment]
what about other products?

**Comment by Arsnael** [comment]
I don't see glowroot yet in the 3 containers, so not closed...

**Comment by chibenwa** [comment]
See https://github.com/linagora/openpaas-james/issues/6#issuecomment-764417178
