### ISSUE TITLE
UserKeyStore API + Memory Implementation + Contract

### ISSUE THREAD

**Issue by LanKhuat** [linagora/openpaas-james#91]
### Objective

In order to support encrypted mailbox we need a storage to store public key for each user. Server will then make use of this key to encrypt user's data.

### How

1. Define a Key object: Key(id: UUID, value: byte[])

- user can have multiple keys. Uploading the same key two times should be idempotent.

2. Implement a memory version of the UserKeyStore, define the APIs along with a contract. UserKeyStore should at least have the following methods:

```
case class KeyId(value: UUID)
case class PublicKey(id: KeyId, payload: Array[Byte])

trait UserPublicKeyStore {
   def save(username: Username, payload: Array[Byte]): Publisher[KeyId]
   def listPublicKeys(username: Username): Publisher[PublicKey] // many
   def retrieveKey(username: Username, id: KeyId): Publisher[PublicKey] // one
   def delete(username: Username, id: KeyId): Publisher[Void]
   def deleteAll(username: Username): Publisher[Void]
}
```

### DoD

Write unit tests for MemoryUserKeyStore to show that it is working properly.

**Comment by Arsnael** [comment]
I don't think a Key should be just a byte[]. If you read about GPG, you actually generate 2 keys: one private (that user uses for encrypting) and one public (used for decrypting). so maybe Key should be more something like:

```
Key {
  byte[] privateKey;
  byte[] publicKey;
}
```
? Might even wanna strong type the keys, not sure...

**Comment by Arsnael** [comment]
Or would a Key would be just a key? But then you need more fields to differentiate if it's public or private, and to match public/private together, if user can have multiple set of keys

**Comment by chibenwa** [comment]
Storing the private key on James side defeats the proposr of encrypting stuff with a key we don't have.

Only the public key should be accessible to TMail backend.

**Comment by rouazana** [comment]
You don't need to store the kind of the key? (RSA/ECC/etc.)

**Comment by chibenwa** [comment]
We will only support RSA keys.

**Comment by rouazana** [comment]
> We will only support RSA keys.

Which size?

**Comment by chibenwa** [comment]
https://github.com/theautonomy/bouncycastle-gpg-example

Based on that example it seems that given the public key bouncy castle don't need such information to encode data.

**Comment by chibenwa** [comment]
Link on the 'how to implement this' https://mvnrepository.com/artifact/org.bouncycastle/bcpg-jdk15on

**Comment by Arsnael** [comment]
Yeah forgot for a sec we don't store the private key... I mixed up as well, you encode with the public key not the private

**Comment by Arsnael** [comment]
Remains to be done:
- Use fingerprint as key id
- Validation of the validity of the pub key
